#################################################
# Application
#################################################

application.name=AI Selenium Framework
application.version=1.0.0

#################################################
# Environment
#################################################

environment=QA
execution.mode=LOCAL

#################################################
# Browser
#################################################

browser=chrome
headless=false
incognito=false

#################################################
# URL
#################################################

base.url=https://www.google.com

#################################################
# Timeout
#################################################

implicit.wait=10
explicit.wait=30
page.load.timeout=60

#################################################
# Screenshot
#################################################

capture.screenshot.on.pass=false
capture.screenshot.on.fail=true

#################################################
# Retry
#################################################

retry.count=2

#################################################
# AI