#==============================
# Application Configuration
#==============================

application.name=AI Selenium Framework
application.version=1.0.0

#==============================
# Execution
#==============================

execution.environment=QA
execution.mode=LOCAL

#==============================
# Browser
#==============================

browser=chrome
headless=false

#==============================
# Timeouts
#==============================

implicit.wait=10
explicit.wait=30
page.load.timeout=60

#==============================
# URL
#==============================

base.url=https://www.google.com